#+STARTUP: content
#+OPTIONS: author:nil toc:nil num:nil 

* STAT 5125 Project

*Topic Sign Up Link*: https://classroom.github.com/a/MWhxJSvT

This project consists of two parts: an oral presentation and a written
report. You may work alone or work with a partner on the project. If you work
with a partner, the two students should give the oral presentation together. The
written report and all source codes should be managed on github.com through the
[[https://classroom.github.com/a/1e3Frc21][submission link]]. *The written report is due on TBA*.


* Teams and Topics

*Submission Link*: https://classroom.github.com/a/1e3Frc21

When you accept the invitation, you can create a new team if you work along or
if you are the first in your team to accept the link, or you can join an
existing team if your partner has created a team.

** Sita Nyame
- [[https://github.com/MichaelHatherly/Publish.jl][Publish.jl]]
** Yiran Qiao
- [[https://github.com/JuliaPy/PyCall.jl][PyCall.jl]] 
** Xinhao Wang
- [[https://github.com/JuliaInterop/MATLAB.jl][MATLAB.jl]]
** Justin Guilfoyle
- [[https://github.com/jump-dev/JuMP.jl][JuMP.jl]]
** Boyang Tang, Fusheng Yang
- [[http://gadflyjl.org/stable/][Gadfly.jl]]
** Jing Wang, Wenting Sun
Use simulation to approximate [[https://en.wikipedia.org/wiki/Poker_probability][poker probabilities]].
** Andrew Slater
Simulating the [[https://en.wikipedia.org/wiki/Craps][Craps game]].


* Presentation schedule <2022-04-11 Mon>

The length of the oral presentation will be 15-20 minutes for each team.

#+begin_src julia :eval no :exports none
using Random
Random.seed!(2022)
teams = shuffle([
    "Sita Nyame",
    "Yiran Qiao",
    "Xinhao Wang",
    "Justin GuilfoyleY",
    "Boyang Tang, Fusheng Yang",
    "Jing Wang, Wenting Sun",
    "Andrew Slater",
    "Graham Roberts"
])
for (i, nm) in enumerate(teams) println("- Team $i: $(nm)") end
#+end_src

- Team 1: Boyang Tang, Fusheng Yang
- Team 2: Graham Roberts
- Team 3: Sita Nyame
- Team 4: Andrew Slater
- Team 5: Jing Wang, Wenting Sun
- Team 6: Justin GuilfoyleY
- Team 7: Yiran Qiao
- Team 8: Xinhao Wang
